const exercises=[
{id:1,title:'Mobilidade de ombro',category:'mobilidade',emoji:'🙆',duration:'12 min',desc:'Sequência demonstrativa de movimentos suaves para mobilidade do ombro, quando orientada por profissional.',steps:['Posicione-se de forma confortável e estável.','Realize o movimento lentamente, sem buscar amplitude forçada.','Mantenha respiração tranquila durante a execução.','Siga apenas o número de repetições indicado pelo seu profissional.']},
{id:2,title:'Alongamento cervical',category:'alongamento',emoji:'🧘',duration:'6 min',desc:'Conteúdo educativo demonstrativo sobre mobilidade e alongamento da região cervical.',steps:['Sente-se com apoio e postura confortável.','Faça movimentos leves e controlados.','Evite movimentos bruscos ou sustentados além do confortável.','Interrompa se houver piora dos sintomas.']},
{id:3,title:'Fortalecimento do joelho',category:'fortalecimento',emoji:'🦵',duration:'9 min',desc:'Exemplo de exercício de fortalecimento que deve ser utilizado apenas quando incluído no plano do paciente.',steps:['Confirme o exercício indicado pelo fisioterapeuta.','Mantenha o movimento controlado.','Não aumente carga ou repetições por conta própria.','Registre a sessão ao finalizar.']},
{id:4,title:'Mobilidade de tornozelo',category:'mobilidade',emoji:'🦶',duration:'7 min',desc:'Demonstração de mobilidade do tornozelo para planos orientados.',steps:['Apoie-se com segurança.','Movimente dentro de uma amplitude confortável.','Evite compensações do restante do corpo.','Siga o tempo definido no seu plano.']},
{id:5,title:'Rotina de postura',category:'prevencao',emoji:'🪑',duration:'5 min',desc:'Conteúdo preventivo com orientações gerais para variar posições ao longo do dia.',steps:['Observe sua posição atual.','Alterne posições ao longo do dia.','Inclua pausas breves quando necessário.','Procure orientação individual se houver sintomas persistentes.']},
{id:6,title:'Mobilidade de quadril',category:'mobilidade',emoji:'🚶',duration:'10 min',desc:'Conteúdo demonstrativo de mobilidade do quadril, sem prescrição individual.',steps:['Escolha um apoio estável.','Realize o movimento devagar.','Não force amplitudes desconfortáveis.','Use o conteúdo apenas quando compatível com sua orientação.']}
];
const professionals=[
{name:'Dra. Ana Beatriz',initials:'AB',specialty:'Ortopédica',city:'Fortaleza - CE',mode:'Presencial e online',exp:'8 anos',rating:'4,9'},
{name:'Dr. Lucas Mendes',initials:'LM',specialty:'Esportiva',city:'Sobral - CE',mode:'Presencial',exp:'6 anos',rating:'4,8'},
{name:'Dra. Carla Nunes',initials:'CN',specialty:'Geriátrica',city:'Fortaleza - CE',mode:'Presencial e domiciliar',exp:'10 anos',rating:'4,9'},
{name:'Dr. Rafael Lima',initials:'RL',specialty:'Neurológica',city:'Itapipoca - CE',mode:'Presencial e online',exp:'7 anos',rating:'4,7'},
{name:'Clínica Movimento',initials:'CM',specialty:'Ortopédica',city:'Fortaleza - CE',mode:'Clínica',exp:'12 anos',rating:'4,8'},
{name:'Dra. Paula Reis',initials:'PR',specialty:'Esportiva',city:'Caucaia - CE',mode:'Online e presencial',exp:'5 anos',rating:'4,8'}
];
const history=[{name:'Mobilidade de ombro',date:'Hoje, 08:20',time:'12 min'},{name:'Alongamento cervical',date:'Ontem, 19:05',time:'6 min'},{name:'Mobilidade de tornozelo',date:'15 set, 17:40',time:'7 min'}];
let sessions=Number(localStorage.getItem('movifisioSessions')||8);
let weekDone=Number(localStorage.getItem('movifisioWeek')||3);
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=qs('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(id){qs(id).classList.add('open');qs(id).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModals(){qsa('.modal').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')});document.body.style.overflow=''}
qsa('[data-close]').forEach(b=>b.onclick=closeModals);qsa('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
function cardExercise(e){return `<article class="exercise-card"><div class="exercise-cover">${e.emoji}<span class="duration">${e.duration}</span></div><div class="exercise-body"><small>${e.category.toUpperCase()}</small><h4>${e.title}</h4><p>${e.desc}</p><button data-open-exercise="${e.id}">Ver passo a passo</button></div></article>`}
function bindExercises(){qsa('[data-open-exercise]').forEach(b=>b.onclick=()=>openExercise(Number(b.dataset.openExercise)))}
function renderExercises(list=exercises){qs('#exerciseLibrary').innerHTML=list.map(cardExercise).join('');qs('#homeExercises').innerHTML=exercises.slice(0,3).map(cardExercise).join('');bindExercises()}
function openExercise(id){const e=exercises.find(x=>x.id===id);if(!e)return;qs('#exerciseTitle').textContent=e.title;qs('#exerciseCategory').textContent=e.category.toUpperCase();qs('#exerciseDesc').textContent=e.desc;qs('#exerciseSteps').innerHTML=e.steps.map((s,i)=>`<div class="step"><span>${i+1}</span><p>${s}</p></div>`).join('');qs('#completeExercise').dataset.exercise=id;qs('#videoTimer').textContent='00:00';qs('#playDemo').textContent='▶ Reproduzir demonstração';openModal('#exerciseModal')}
function renderProfessionals(list=professionals){const html=list.map((p,i)=>`<article class="pro-card"><div class="pro-card-top"><div class="pro-photo">${p.initials}</div><div><h4>${p.name}</h4><p>Fisioterapia ${p.specialty}</p><div class="rating">★★★★★ <span>${p.rating}</span></div></div></div><div class="pro-meta"><span>${p.city}</span><span>${p.mode}</span><span>${p.exp}</span></div><button data-pro="${professionals.indexOf(p)}">Ver perfil e contato</button></article>`).join('');qs('#professionalGrid').innerHTML=html;qs('#publicProfessionalGrid').innerHTML=professionals.slice(0,3).map((p,i)=>`<article class="pro-card"><div class="pro-card-top"><div class="pro-photo">${p.initials}</div><div><h4>${p.name}</h4><p>Fisioterapia ${p.specialty}</p><div class="rating">★★★★★ <span>${p.rating}</span></div></div></div><div class="pro-meta"><span>${p.city}</span><span>${p.mode}</span></div><button data-pro="${i}">Conhecer perfil</button></article>`).join('');qsa('[data-pro]').forEach(b=>b.onclick=()=>openProfessional(Number(b.dataset.pro)))}
function openProfessional(i){const p=professionals[i];qs('#proPhoto').textContent=p.initials;qs('#proName').textContent=p.name;qs('#proSpecialty').textContent='Fisioterapia '+p.specialty;qs('#proMode').textContent=p.mode;qs('#proCity').textContent=p.city;qs('#proExp').textContent=p.exp;openModal('#professionalModal')}
function renderHistory(){qs('#historyList').innerHTML=history.map(h=>`<div class="history-row"><div><b>${h.name}</b><span>${h.date}</span></div><strong>${h.time} • concluído</strong></div>`).join('');qs('#sessionsCount').textContent=sessions;qs('#goalRing').textContent=`${Math.min(weekDone,4)}/4`}
function renderBars(){const data=[2,1,3,0,2,1,3];const days=['S','T','Q','Q','S','S','D'];qs('#progressBars').innerHTML=data.map((v,i)=>`<div class="bar-col"><div style="--h:${v?50+v*38:6}px"></div><span>${days[i]}</span></div>`).join('')}
function switchView(id){qsa('.view').forEach(v=>v.classList.toggle('active',v.id===id));qsa('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={inicioDash:'Seu acompanhamento',exercicios:'Biblioteca de exercícios',progresso:'Meu progresso',profissionaisView:'Profissionais e clínicas',prevencao:'Prevenção e educação',perfil:'Meu perfil'};qs('#viewTitle').textContent=titles[id]||'MoviFisio';qs('#demo').scrollIntoView({behavior:'smooth',block:'start'})}
qsa('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));qsa('[data-section]').forEach(b=>b.onclick=()=>switchView(b.dataset.section));qsa('[data-scroll]').forEach(b=>b.onclick=()=>qs('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
function auth(mode='cadastro'){qs('#authTitle').textContent=mode==='login'?'Entrar na MoviFisio':'Crie sua conta';openModal('#authModal')}
qs('#btnLogin').onclick=()=>auth('login');qs('#btnCadastro').onclick=()=>auth();qs('#btnComecar').onclick=()=>auth();qs('#ctaCreate').onclick=()=>auth();
qsa('[data-role]').forEach(b=>b.onclick=()=>{qsa('[data-role]').forEach(x=>x.classList.toggle('active',x===b));qs('#professionalFields').classList.toggle('hidden',b.dataset.role!=='profissional')});
qs('#authForm').onsubmit=e=>{e.preventDefault();closeModals();toast('Conta demonstrativa criada. Bem-vindo à MoviFisio!');setTimeout(()=>qs('#demo').scrollIntoView({behavior:'smooth'}),350)};
qs('#btnDemo').onclick=()=>qs('#demo').scrollIntoView({behavior:'smooth'});
qs('#exerciseSearch').oninput=filterExercises;qs('#exerciseFilter').onchange=filterExercises;function filterExercises(){const t=qs('#exerciseSearch').value.toLowerCase();const c=qs('#exerciseFilter').value;renderExercises(exercises.filter(e=>(e.title+' '+e.desc).toLowerCase().includes(t)&&(c==='todos'||e.category===c)))}
qs('#professionalSearch').oninput=filterPros;qs('#specialtyFilter').onchange=filterPros;function filterPros(){const t=qs('#professionalSearch').value.toLowerCase();const s=qs('#specialtyFilter').value;renderProfessionals(professionals.filter(p=>(p.name+' '+p.specialty+' '+p.city).toLowerCase().includes(t)&&(s==='todos'||p.specialty===s)))}
let playing=false,timerInt,seconds=0;qs('#playDemo').onclick=()=>{playing=!playing;if(playing){qs('#playDemo').textContent='❚❚ Pausar';timerInt=setInterval(()=>{seconds++;qs('#videoTimer').textContent=`00:${String(seconds).padStart(2,'0')}`;if(seconds>=15){clearInterval(timerInt);playing=false;seconds=0;qs('#playDemo').textContent='↻ Repetir demonstração'}},1000)}else{clearInterval(timerInt);qs('#playDemo').textContent='▶ Continuar'}};
qs('#completeExercise').onclick=()=>{sessions++;weekDone=Math.min(4,weekDone+1);localStorage.setItem('movifisioSessions',sessions);localStorage.setItem('movifisioWeek',weekDone);renderHistory();closeModals();toast('Sessão registrada no seu progresso.')};
qs('#markSession').onclick=()=>{weekDone=Math.min(4,weekDone+1);sessions++;localStorage.setItem('movifisioSessions',sessions);localStorage.setItem('movifisioWeek',weekDone);renderHistory();toast(weekDone>=4?'Meta semanal atingida no protótipo!':'Sessão adicionada à meta semanal.')};
qs('#requestAppointment').onclick=()=>{const d=qs('#appointmentDate').value;if(!d)return toast('Escolha uma data para a solicitação.');closeModals();toast('Solicitação demonstrativa enviada ao profissional.')};
qsa('[data-article]').forEach(b=>b.onclick=()=>{qs('#articleTitle').textContent=b.dataset.article;openModal('#articleModal')});
qsa('[data-plan]').forEach(b=>b.onclick=()=>toast(`Plano ${b.dataset.plan}: ação demonstrativa do protótipo.`));qs('#btnProfessional').onclick=()=>{auth();setTimeout(()=>qsa('[data-role="profissional"]')[0].click(),50)};qs('#editProfile').onclick=()=>toast('Edição de perfil demonstrativa.');qs('#fontToggle').onclick=()=>document.body.classList.toggle('large-text');qs('#contrastToggle').onclick=()=>document.body.classList.toggle('high-contrast');
renderExercises();renderProfessionals();renderHistory();renderBars();
